services:
  - type: web
    name: code-to-flowchart
    env: python
    buildCommand: |
      curl -sSL https://raw.githubusercontent.com/weibeld/heroku-buildpack-graphviz/master/bin/install-graphviz | sh
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PATH
        value: /app/.apt/usr/bin:$PATH
