# render.yaml

services:
  - type: web
    name: flowchart-app
    env: python
    build:
      commands:
        # Update and install Graphviz
        - apt-get update && apt-get install -y graphviz
    start:
      command: python app.py
    env_vars:
      - key: FLASK_ENV
        value: production
    plan: free
